### ISSUE TITLE
la multi ani frt!

### ISSUE THREAD

**Issue by MaziluMihaiDenis** [PeterPancake666/2048_In_C#4]
cam atat pe anu asta

**Comment by MaziluMihaiDenis** [comment]
si codu asta salveaza high score-ul

```
#include <stdio.h>
#include <stdlib.h>

void save_highest_score(int score);
int _get_previous_highest_score();
void _write_new_score(int score);

void save_highest_score(int score)
{
    if(_get_previous_highest_score() < score)
        _write_new_score(score);
}

int _get_previous_highest_score()
{
    FILE* file;
    int score;

    file = fopen("C:\\Users\\mazil\\AppData\\Roaming\\2048inC.txt", "r");
    fscanf(file, "%d", &score);
    fclose(file);
    return score;
}

void _write_new_score(int score)
{
    FILE* file;

    file = fopen("C:\\Users\\mazil\\AppData\\Roaming\\2048inC.txt", "w");

    fprintf(file, "%d", score);
    fclose(file);
}
```

si mai trebuie modificat la lose doar adaugi prima functie :)

**Comment by PeterPancake695** [comment]
La multi ani! Sa ai un 2023 plin de bucurii, zambate si fara erori segfault! Lucram la un sistem de high-score deja. Daca vrei sa stii la ce mai lucrez iti dau trello-ul meu:
![2023-01-01_22-47](https://user-images.githubusercontent.com/96543374/210184186-b13aff04-d1e2-430d-b8d3-cb5a53d538be.png)

PS: nu uita sa dai download la beta release ca e foarte epikk
